/*
 * Constants.h
 *
 *  Created on: May 23, 2013
 *      Author: omergilad
 */

#ifndef CONSTANTS_H_
#define CONSTANTS_H_




#undef ANDROID_PORT_DEBUG



// Game types
#define GAME_TYPE_SIMON1 0
#define GAME_TYPE_SIMON2 1
#define GAME_TYPE_FOTAQ 2
#define GAME_TYPE_INDY_FOA 3




#define GAME_SCREEN_WIDTH 320
#define GAME_SCREEN_HEIGHT 200

#define SHADER_SCALING_MAX_RESOLUTION_W 1280
#define SHADER_SCALING_MAX_RESOLUTION_H 800

#define SHADER_SCALING_ULTRA_MAX_RESOLUTION_W 1920
#define SHADER_SCALING_ULTRA_MAX_RESOLUTION_H 1200



#define SKIP_X 0
#define SKIP_Y 0
#define SKIP_W 0.09

#define REVEAL_ITEMS_X 0.91
#define REVEAL_ITEMS_Y 0
#define REVEAL_ITEMS_W 0.09

#define CONTROL_MODE_X 0
#define CONTROL_MODE_Y 0
#define CONTROL_MODE_W 0.09

#define MENU_X 0
#define MENU_Y 0
#define MENU_W 0.1

#define FRAME_W 0.1

#define BIG_ACTION_ICON_X 0.425
#define BIG_ACTION_ICON_Y 0.3
#define BIG_ACTION_ICON_W 0.15

#define SMALL_ACTION_ICON_W 		0.08
#define SMALL_ACTION_ICON_PADDING 		14

#define TOUCH_INDICATOR_W 0.035
#define TOUCH_INDICATOR_MIN_SCALE_W 0.04
#define TOUCH_INDICATOR_MAX_SCALE_W 0.05
#define TOUCH_INDICATOR_SCALE_DURATION 750
#define TOUCH_INDICATOR_INITIAL_FADE_DURATION 100



#define MUSIC_ENHANCED_BY_X 0.1
#define MUSIC_ENHANCED_BY_Y 0.7
#define MUSIC_ENHANCED_BY_W 0.8
#define MUSIC_ENHANCED_BY_BEGIN_TIME 3000
#define MUSIC_ENHANCED_BY_END_TIME 8000

#define CURSOR_W 0.04




// This is the amount of pixels that pad the actual copy area (so that it'll be inside the magnifier image but not on its edges)
#define MAGNIFIER_COPY_RECT_PADDING_PIXELS 1

#define BLACK_PANEL_START_Y 134
#define BLACK_PANEL_END_Y 144

#define BLACK_PANEL_HEIGHT (BLACK_PANEL_END_Y - BLACK_PANEL_START_Y)

#define ARROW_W 0.1
#define ARROW_H 0.14

#define UP_ARROW_X (1 - ARROW_W - 0.01)
#define UP_ARROW_Y 0.37
#define DOWN_ARROW_X (1 - ARROW_W - 0.01)
#define DOWN_ARROW_Y (UP_ARROW_Y + ARROW_H + 0.01)

#define CHAT_BUTTON_W (ARROW_W * 1.6)
#define CHAT_BUTTON_H (ARROW_H * 2 + 0.01)
#define CHAT_BUTTON_X (UP_ARROW_X - CHAT_BUTTON_W - 0.01)
#define CHAT_BUTTON_Y UP_ARROW_Y

#define CHAT_HIT_AREAS_START_Y 136

#define INVENTORY_SCROLL_ARROW_START_X 301
#define INVENTORY_SCROLL_ARROW_END_X 315
#define INVENTORY_FLING_MIN_X 170
#define INVENTORY_FLING_MIN_Y 110
#define INVENTORY_UP_ARROW_X 315
#define INVENTORY_UP_ARROW_Y 160
#define INVENTORY_DOWN_ARROW_X 315
#define INVENTORY_DOWN_ARROW_Y 190


#define CHAT_MODE_CHECK_Y 199
#define BOTTOM_TOOLBAR_CHECK_Y 199

#define POSTCARD_WINDOW_CHECK_Y 105

#define POSTCARD_LOAD_START_X 65
#define POSTCARD_LOAD_START_Y 40
#define POSTCARD_LOAD_END_X 156
#define POSTCARD_LOAD_END_Y 70

#define POSTCARD_SAVE_START_X 65
#define POSTCARD_SAVE_START_Y 71
#define POSTCARD_SAVE_END_X 156
#define POSTCARD_SAVE_END_Y 99

#define POSTCARD_EXIT_START_X 157
#define POSTCARD_EXIT_START_Y 40
#define POSTCARD_EXIT_END_X 235
#define POSTCARD_EXIT_END_Y 71

#define POSTCARD_CONTINUE_CLICK_X 180
#define POSTCARD_CONTINUE_CLICK_Y 80

#define POSTCARD_CLICK_NONE 0
#define POSTCARD_CLICK_SAVE 1
#define POSTCARD_CLICK_LOAD 2
#define POSTCARD_CLICK_EXIT 3

#define WALK_ACTION_MIN_TOUCH_TIME 750

// The amount of movement pixels to ignore when checking for long touch holding
#define WALK_ACTION_TOUCH_SENSITIVITY_PIXELS 5

#define BIG_ACTION_ICON_FADEIN_DURATION 100
#define BIG_ACTION_ICON_FADEOUT_DURATION 600
#define BIG_ACTION_ICON_FADE_MAX_ALPHA 0.8


#define HOTSPOT_SWITCH_FADEOUT_DURATION 150
#define HOTSPOT_LEAVE_FADEOUT_DURATION 1250

#define ACTION_BLINK_FADE_DURATION 125
#define ACTION_BLINK_REPEAT_COUNT 3
#define ACTION_ENTER_FADEIN_DURATION 500
#define ACTION_LEAVE_FADEOUT_DURATION 350

#define WALK_ICON_SINGLE_TAP_FADEIN_DURATION 100
#define WALK_ICON_SINGLE_TAP_FADEOUT_DURATION 400
#define WALK_ICON_SINGLE_TAP_MAX_ALPHA 0.75

#define REVEAL_ITEMS_FADEIN_DURATION 100
#define REVEAL_ITEMS_STAY_DURATION 2000
#define REVEAL_ITEMS_FADEOUT_DURATION 500

#define AUTOLOAD_SAFETY_TIME_INTERVAL 1000

#define SHADER_TYPE_VERTEX 0
#define SHADER_TYPE_FRAGMENT 1
#define SHADER_TYPE_LQ_VERTEX 2
#define SHADER_TYPE_LQ_FRAGMENT 3

#define SCALING_OPTION_SHADER 0
#define SCALING_OPTION_SOFT 1
#define SCALING_OPTION_NONE 2
#define SCALING_OPTION_LQ_SHADER 3


#define GAME_EVENT_SCALER_FALLBACK 0
#define GAME_EVENT_SHOULD_TEST_SHADER 1
#define GAME_EVENT_SHADER_TEST_SUCCESS 2
#define GAME_EVENT_SHADER_TEST_FAILURE 3
#define GAME_EVENT_LOAD_SUCCESS 4
#define GAME_EVENT_LOAD_FAILURE 5
#define GAME_EVENT_SAVE_SUCCESS 6
#define GAME_EVENT_SAVE_FAILURE 7
#define GAME_EVENT_SAVE_CANCELLED 8
#define GAME_EVENT_HEBREW_TITLE_GONE 9
#define GAME_EVENT_POSTCARD_SHOWN 10
#define GAME_EVENT_SHOW_MENU 11
#define GAME_EVENT_SCALER_LQ_FALLBACK 12
#define GAME_EVENT_USE_ULTRA_MODE 13


// These values are VERY important!
// They take into account the number of frames shown in the game's first animation, and how much it takes overall.
#define RENDER_MEASURE_SKIPPED_FRAMES 3
#define RENDER_MEASURE_COUNT_MAX 7
#define RENDER_MEASURE_THRESHOLD 100
#define RENDER_MEASURE_MAX_TEST_TIME 3000

#define LOW_QUALITY_SHADER_SCALING_FACTOR 3

// Interval between clicks to prevent Simon from going idle
#define IDLE_PREVENTION_CLICK_INTERVAL 5000
// Coordinates for idle prevention click
#define IDLE_PREVENTION_CLICK_X 0
#define IDLE_PREVENTION_CLICK_Y 140

#define SAVE_TIMEOUT 5000

#define HIT_AREA_MAX 100

#define DISTANCE_THRESHOLD 50

#define WALK_ASSIST_BORDER_SIZE_X 25
#define WALK_ASSIST_BORDER_SIZE_Y 5

#define ENHANCED_MUSIC_VOLUME 80


#define OUTSIDE_DRAGON_CAVE_WORKAROUND_MIN_X 275
#define OUTSIDE_DRAGON_CAVE_WORKAROUND_MIN_Y 0
#define OUTSIDE_DRAGON_CAVE_WORKAROUND_MAX_X 319
#define OUTSIDE_DRAGON_CAVE_WORKAROUND_MAX_Y 35
#define OUTSIDE_DRAGON_CAVE_WORKAROUND_TARGET_X 298
#define OUTSIDE_DRAGON_CAVE_WORKAROUND_TARGET_Y 10



/**
 * Simon 1 action ids
 */
#define ACTION_WALK 101
#define ACTION_LOOK 102
#define ACTION_OPEN 103
#define ACTION_MOVE 104
#define ACTION_CONSUME 105
#define ACTION_PICK 106
#define ACTION_CLOSE 107
#define ACTION_USE 108
#define ACTION_TALK 109
#define ACTION_REMOVE 110
#define ACTION_WEAR 111
#define ACTION_GIVE 112


#endif /* CONSTANTS_H_ */
